config/routes.rb
Rails.application.routes.draw do
  resources :powers
  resources :planets
  resources :aliens
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alien.rb
class Alien < ApplicationRecord
    belongs_to :planet

    has_many :alien_powers
    has_many :powers, through: :alien_powers

end

app/models/alien_power.rb
class AlienPower < ApplicationRecord
  belongs_to :alien
  belongs_to :power
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/planet.rb
class Planet < ApplicationRecord
end

app/models/power.rb
class Power < ApplicationRecord

    has_many :alien_powers
    has_many :aliens, through: :alien_powers

    validates_presence_of :name

end

app/controllers/aliens_controller.rb
class AliensController < ApplicationController
  before_action :set_alien, only: [:show, :edit, :update, :destroy]

  # GET /aliens
  # GET /aliens.json
  def index
    @aliens = Alien.all
  end

  # GET /aliens/1
  # GET /aliens/1.json
  def show
  end

  # GET /aliens/new
  def new
    @alien = Alien.new
  end

  # GET /aliens/1/edit
  def edit
  end

  # POST /aliens
  # POST /aliens.json
  def create
    @alien = Alien.new(alien_params)

    respond_to do |format|
      if @alien.save
        format.html { redirect_to @alien, notice: 'Alien adicionado com sucesso.' }
        format.json { render :show, status: :created, location: @alien }
      else
        format.html { render :new }
        format.json { render json: @alien.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aliens/1
  # PATCH/PUT /aliens/1.json
  def update
    respond_to do |format|
      if @alien.update(alien_params)
        format.html { redirect_to @alien, notice: 'Alien atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @alien }
      else
        format.html { render :edit }
        format.json { render json: @alien.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aliens/1
  # DELETE /aliens/1.json
  def destroy
    @alien.destroy
    respond_to do |format|
      format.html { redirect_to aliens_url, notice: 'Alien deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alien
      @alien = Alien.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alien_params
      params.require(:alien).permit(:name, :age, :planet_id, :power_ids => [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]

  # GET /planets
  # GET /planets.json
  def index
    @planets = Planet.all
  end

  # GET /planets/1
  # GET /planets/1.json
  def show
  end

  # GET /planets/new
  def new
    @planet = Planet.new
  end

  # GET /planets/1/edit
  def edit
  end

  # POST /planets
  # POST /planets.json
  def create
    @planet = Planet.new(planet_params)

    respond_to do |format|
      if @planet.save
        format.html { redirect_to @planet, notice: 'Planeta adicionado com sucesso.' }
        format.json { render :show, status: :created, location: @planet }
      else
        format.html { render :new }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planets/1
  # PATCH/PUT /planets/1.json
  def update
    respond_to do |format|
      if @planet.update(planet_params)
        format.html { redirect_to @planet, notice: 'Planeta atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1
  # DELETE /planets/1.json
  def destroy
    @planet.destroy
    respond_to do |format|
      format.html { redirect_to planets_url, notice: 'Planeta excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      @planet = Planet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def planet_params
      params.require(:planet).permit(:name)
    end
end

app/controllers/powers_controller.rb
class PowersController < ApplicationController
  before_action :set_power, only: [:show, :edit, :update, :destroy]

  # GET /powers
  # GET /powers.json
  def index
    @powers = Power.all
  end

  # GET /powers/1
  # GET /powers/1.json
  def show
  end

  # GET /powers/new
  def new
    @power = Power.new
  end

  # GET /powers/1/edit
  def edit
  end

  # POST /powers
  # POST /powers.json
  def create
    @power = Power.new(power_params)

    respond_to do |format|
      if @power.save
        format.html { redirect_to @power, notice: 'Poder adicionado com sucesso.' }
        format.json { render :show, status: :created, location: @power }
      else
        format.html { render :new }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /powers/1
  # PATCH/PUT /powers/1.json
  def update
    respond_to do |format|
      if @power.update(power_params)
        format.html { redirect_to @power, notice: 'Poder atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @power }
      else
        format.html { render :edit }
        format.json { render json: @power.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /powers/1
  # DELETE /powers/1.json
  def destroy
    @power.destroy
    respond_to do |format|
      format.html { redirect_to powers_url, notice: 'Poder excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_power
      @power = Power.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def power_params
      params.require(:power).permit(:name)
    end
end

app/helpers/aliens_helper.rb
module AliensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planets_helper.rb
module PlanetsHelper
end

app/helpers/powers_helper.rb
module PowersHelper
end

app/views/aliens/_form.html.erb
<%= form_with(model: alien, local: true) do |form| %>
  <% if alien.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alien.errors.count, "error") %> prohibited this alien from being saved:</h2>

      <ul>
      <% alien.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :planeta %>
    <%= collection_select(:alien, :planet_id, Planet.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :name, id: :alien_name %>
  </div>

  <div class="field">
    <%= form.label :idade %>
    <%= form.number_field :age, id: :alien_age %>
  </div>

  <div class="field">
    <%= form.label :poder %>
    <%= collection_check_boxes(:alien, :power_ids, Power.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/aliens/edit.html.erb
<h1>Editando Alien</h1>

<%= render 'form', alien: @alien %>

<%= link_to 'Visualizar', @alien %> |
<%= link_to 'Voltar', aliens_path %>

app/views/aliens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alienígenas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Planeta</th>
      <th>Idade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aliens.each do |alien| %>
      <tr>
        <td><%= alien.name %></td>
        <td><%= alien.planet.name %></td>
        <td><%= alien.age %></td>
        <td><%= link_to 'Visualizar', alien %></td>
        <td><%= link_to 'Editar', edit_alien_path(alien) %></td>
        <td><%= link_to 'Deletar', alien, method: :delete, data: { confirm: "Você tem certeza que deseja excluir o alien #{alien.name}?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Alien', new_alien_path %>

app/views/aliens/new.html.erb
<h1>Novo Alien</h1>

<%= render 'form', alien: @alien %>

<%= link_to 'Voltar', aliens_path %>

app/views/aliens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @alien.name %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @alien.age %>
</p>

<%= link_to 'Editar', edit_alien_path(@alien) %> |
<%= link_to 'Voltar', aliens_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AliensRubyOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/planets/_form.html.erb
<%= form_with(model: planet, local: true) do |form| %>
  <% if planet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(planet.errors.count, "error") %> prohibited this planet from being saved:</h2>

      <ul>
      <% planet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :name, id: :planet_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/planets/edit.html.erb
<h1>Editando Planeta</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Visuzalizar', @planet %> |
<%= link_to 'Voltar', planets_path %>

app/views/planets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Planetas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planets.each do |planet| %>
      <tr>
        <td><%= planet.name %></td>
        <td><%= link_to 'Show', planet %></td>
        <td><%= link_to 'Edit', edit_planet_path(planet) %></td>
        <td><%= link_to 'Destroy', planet, method: :delete, data: { confirm: "Você tem certeza que deseja excluir o planeta #{planet.name}?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Planeta', new_planet_path %>

app/views/planets/new.html.erb
<h1>Novo Planeta</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Voltar', planets_path %>

app/views/planets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @planet.name %>
</p>

<%= link_to 'Editar', edit_planet_path(@planet) %> |
<%= link_to 'Voltar', planets_path %>

app/views/powers/_form.html.erb
<%= form_with(model: power, local: true) do |form| %>
  <% if power.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(power.errors.count, "error") %> prohibited this power from being saved:</h2>

      <ul>
      <% power.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :name, id: :power_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/powers/edit.html.erb
<h1>Editando Poder</h1>

<%= render 'form', power: @power %>

<%= link_to 'Mostrar', @power %> |
<%= link_to 'Voltar', powers_path %>

app/views/powers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poderes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @powers.each do |power| %>
      <tr>
        <td><%= power.name %></td>
        <td><%= link_to 'Visualizar', power %></td>
        <td><%= link_to 'Editar', edit_power_path(power) %></td>
        <td><%= link_to 'Deletar', power, method: :delete, data: { confirm: "Você tem certeza que deseja excluir o poder #{power.name}?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Poder', new_power_path %>

app/views/powers/new.html.erb
<h1>Novo Poder</h1>

<%= render 'form', power: @power %>

<%= link_to 'Back', powers_path %>

app/views/powers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @power.name %>
</p>

<%= link_to 'Editar', edit_power_path(@power) %> |
<%= link_to 'Voltar', powers_path %>